name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write # to be able to publish a GitHub release
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run semantic-release
      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
